# Generated by Django 2.2.28 on 2023-08-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_newmo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newmo2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aul', models.BigIntegerField()),
            ],
        ),
    ]
